id: ingestion-api
kind: Pod
apiVersion: v1beta1
desiredState:
  manifest:
    version: v1beta1
    id: ingestion-api
    containers:
      - name: ingestion-api
        image: samsara/ingestion-api:test
        cpu: 1000
        ports:
          - name: http
            containerPort: 9000
          - name: supervisord
            containerPort: 15000
        volumeMounts:
          - name: logs
            mountPath: /logs
    volumes:
      - name: logs
        source:
          emptyDir: {}
labels:
  name: ingestion-api
